// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRarVrK0iM3ZXMdHj7Zcl5XAjKViu4sXs',
    appId: '1:867767870522:web:24b0882925afaeddbf4103',
    messagingSenderId: '867767870522',
    projectId: 'musfer-ecommerce',
    authDomain: 'musfer-ecommerce.firebaseapp.com',
    storageBucket: 'musfer-ecommerce.firebasestorage.app',
    measurementId: 'G-13GM012GJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx-pn3xp9onY3W1yUOaZLsEVO_fbyhLK8',
    appId: '1:867767870522:android:8a2d88acf89ec9adbf4103',
    messagingSenderId: '867767870522',
    projectId: 'musfer-ecommerce',
    storageBucket: 'musfer-ecommerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeyx0ccpET0u8GSJ1n6lxnuAUZgQU333E',
    appId: '1:867767870522:ios:d1c0654dbb6afef9bf4103',
    messagingSenderId: '867767870522',
    projectId: 'musfer-ecommerce',
    storageBucket: 'musfer-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeyx0ccpET0u8GSJ1n6lxnuAUZgQU333E',
    appId: '1:867767870522:ios:d1c0654dbb6afef9bf4103',
    messagingSenderId: '867767870522',
    projectId: 'musfer-ecommerce',
    storageBucket: 'musfer-ecommerce.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRarVrK0iM3ZXMdHj7Zcl5XAjKViu4sXs',
    appId: '1:867767870522:web:5113a15bbac3bd85bf4103',
    messagingSenderId: '867767870522',
    projectId: 'musfer-ecommerce',
    authDomain: 'musfer-ecommerce.firebaseapp.com',
    storageBucket: 'musfer-ecommerce.firebasestorage.app',
    measurementId: 'G-XGCCVSF45B',
  );
}
